#  集成config配置文件
server: 
  port: 9527
 
spring: 
  application:
    name: SpringCloudBorn-zuul-gateway
  config: 
    name: ${spring.application.name}
    profile: ${config.profile:dev}  
    discovery: 
          enabled: true #使用服务发现组件中的Config Server，默认false
          service-id: config-server  #Config Server的名字，默认configserver  
  profiles:  
    active: test
           
