server: 
  port: 3344 
  
  
spring:
  application:
    name:  SpringCloudBorn-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/18753377299/springCloudConfig.git #GitHub上面的git仓库名字
 #通过下面地址进行访问可以请求到github上面的配置文件：http://localhost:3344/application-test.yml

