server: 
  port: 80


#feign: 
#  hystrix: 
#    enabled: true
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
#      defaultZone: http://localhost:7001/eureka
        #集群
       defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/      
  instance:
    instance-id: microservicecloud-dept80
    prefer-ip-address: true     #访问路径可以显示IP地址  